project:
  type: website

website:
  title: "Zahid Asghar"
  
  favicon: "profile.jpg"
  
  page-footer:
    center: |
      <span class="container"><strong>[Contact Zahid Asghar](mailto:g.zahid@gmail.com){target="_blank"}</strong></span>
    left: |
      <span class="container"><strong>Made with [Posit Quarto](https://quarto.org/){target="_blank"}</strong></span>
    right: |
      <span class="container"><strong>[Github Repo](https://github.com/zahedasghar/Blog){target="_blank"}</strong></span>
    background: "#004E4F"
    
  navbar:
    
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: posts

      - href: resume.qmd
        text: Resume
        
    right:
      - icon: mastodon
        href: hhttps://mastodon.social/@zahidasghar
        aria-label: Quarto Mastodon
      - icon: twitter
        href: https://twitter.com/zahedasghar
        aria-label: Quarto Twitter
      - icon: linkedin
        href: https://linkedin.com/in/zahidasghar
        aria-label: Quarto LinkedIn
      - icon: github
        href: https://github.com/zahedasghar/
        aria-label: Quarto Github
        
  search: 
    location: navbar
    type: overlay

format:
  html:
    theme:
      light: [cosmo, theme_light_custom.scss]
      dark: [cosmo, theme_dark_custom.scss]
    css: styles.css
    citations-hover: true
    code-link: true
    code-fold: show
    code-tools: false
    code-block-border-left: "#004E4F"
    

    
editor: visual

